# Generated by Django 3.2.3 on 2021-05-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_code', models.CharField(max_length=2, unique=True, verbose_name='学年コード')),
                ('grade_text', models.CharField(max_length=10, unique=True, verbose_name='学年')),
            ],
            options={
                'verbose_name': '学年',
                'verbose_name_plural': '学年マスタ',
                'ordering': ['grade_code'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=4, verbose_name='単元コード')),
                ('unit_text', models.CharField(max_length=100, verbose_name='単元')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grade', verbose_name='学年')),
            ],
            options={
                'verbose_name': '単元',
                'verbose_name_plural': '単元マスタ',
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=100, unique=True, verbose_name='問題')),
                ('answer_text', models.CharField(max_length=100, verbose_name='解答')),
                ('source_text', models.CharField(max_length=100, verbose_name='出典')),
                ('url_text', models.CharField(max_length=200, null=True, verbose_name='URL')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit', verbose_name='単元')),
            ],
            options={
                'verbose_name': '設問',
                'verbose_name_plural': '設問マスタ',
                'ordering': ['unit', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('grade', 'unit_code'), name='unit_unique'),
        ),
    ]
