# Generated by Django 3.2.3 on 2021-05-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
            ],
            options={
                'verbose_name': 'プリントヘッダ',
                'verbose_name_plural': 'プリントヘッダ',
            },
        ),
        migrations.CreateModel(
            name='PrintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='問題数')),
                ('printhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printhead', verbose_name='プリントヘッダ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unit', verbose_name='単元')),
            ],
            options={
                'verbose_name': 'プリント明細',
                'verbose_name_plural': 'プリント明細',
            },
        ),
    ]
