# Generated by Django 3.2.3 on 2021-06-07 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_printdetail_printhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='ファイル')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'プリントアーカイブ',
                'verbose_name_plural': 'プリントアーカイブ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='printdetail',
            options={'ordering': ['printhead', 'unit'], 'verbose_name': 'プリント明細', 'verbose_name_plural': 'プリント明細'},
        ),
        migrations.AlterField(
            model_name='printdetail',
            name='printhead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.printhead', verbose_name='プリントヘッダ'),
        ),
        migrations.AddConstraint(
            model_name='printdetail',
            constraint=models.UniqueConstraint(fields=('printhead', 'unit'), name='printdetail_unique'),
        ),
    ]
