# Generated by Django 3.2.3 on 2021-06-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210608_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='printhead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='api.printhead', verbose_name='プリントヘッダ'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to='archive', verbose_name='ファイル'),
        ),
    ]
