# Generated by Django 3.2.3 on 2021-06-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210612_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='printhead',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='printhead',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='パスワード'),
        ),
    ]
