# Generated by Django 3.2.3 on 2021-06-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210614_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=100, verbose_name='形式')),
                ('template_path', models.CharField(max_length=100, verbose_name='テンプレートのパス')),
                ('cover_path', models.CharField(max_length=100, null=True, verbose_name='表紙のパス')),
            ],
            options={
                'verbose_name': 'プリント形式',
                'verbose_name_plural': 'プリント形式',
            },
        ),
    ]
