# Generated by Django 3.2.3 on 2021-06-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_printtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printtype',
            name='cover_path',
        ),
        migrations.RemoveField(
            model_name='printtype',
            name='template_path',
        ),
        migrations.AddField(
            model_name='printtype',
            name='cover',
            field=models.FileField(null=True, upload_to='cover', verbose_name='表紙'),
        ),
        migrations.AddField(
            model_name='printtype',
            name='template',
            field=models.FileField(default='', upload_to='template', verbose_name='テンプレート'),
            preserve_default=False,
        ),
    ]
