# Generated by Django 3.2.3 on 2021-06-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210616_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='printhead',
            name='printtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.printtype', verbose_name='形式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archive',
            name='printhead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to='api.printhead', verbose_name='プリントヘッダ'),
        ),
        migrations.AlterField(
            model_name='printhead',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='printhead',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='printtype',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='cover', verbose_name='表紙'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
