# Generated by Django 3.2.3 on 2021-07-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210701_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printdetail',
            options={'ordering': ['printhead'], 'verbose_name': 'プリント明細', 'verbose_name_plural': 'プリント明細'},
        ),
        migrations.RemoveConstraint(
            model_name='printdetail',
            name='printdetail_unique',
        ),
        migrations.RemoveField(
            model_name='printdetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='printdetail',
            name='units',
            field=models.ManyToManyField(to='api.Unit', verbose_name='単元'),
        ),
    ]
